
package com.balanceador.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "estadoServidor", targetNamespace = "http://servicio.balanceador.com/", wsdlLocation = "http://localhost:8080/BalanceadorClienteServidorUmbralProcesos/Balanceador?wsdl")
public class EstadoServidor
    extends Service
{

    private final static URL ESTADOSERVIDOR_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.balanceador.servicio.EstadoServidor.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.balanceador.servicio.EstadoServidor.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/BalanceadorClienteServidorUmbralProcesos/Balanceador?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/BalanceadorClienteServidorUmbralProcesos/Balanceador?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ESTADOSERVIDOR_WSDL_LOCATION = url;
    }

    public EstadoServidor(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstadoServidor() {
        super(ESTADOSERVIDOR_WSDL_LOCATION, new QName("http://servicio.balanceador.com/", "estadoServidor"));
    }

    /**
     * 
     * @return
     *     returns EstadoServidores
     */
    @WebEndpoint(name = "estadoServidorPort")
    public EstadoServidores getEstadoServidorPort() {
        return super.getPort(new QName("http://servicio.balanceador.com/", "estadoServidorPort"), EstadoServidores.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstadoServidores
     */
    @WebEndpoint(name = "estadoServidorPort")
    public EstadoServidores getEstadoServidorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.balanceador.com/", "estadoServidorPort"), EstadoServidores.class, features);
    }

}
