
package com.balanceador.monitor;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CPUmon", targetNamespace = "http://monitor.balanceador.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CPUmon {


    /**
     * 
     * @return
     *     returns com.balanceador.monitor.Datos
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerProcesamientoMemoriaOcioso", targetNamespace = "http://monitor.balanceador.com/", className = "com.balanceador.monitor.ObtenerProcesamientoMemoriaOcioso")
    @ResponseWrapper(localName = "obtenerProcesamientoMemoriaOciosoResponse", targetNamespace = "http://monitor.balanceador.com/", className = "com.balanceador.monitor.ObtenerProcesamientoMemoriaOciosoResponse")
    public Datos obtenerProcesamientoMemoriaOcioso();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "ejecutarProceso", targetNamespace = "http://monitor.balanceador.com/", className = "com.balanceador.monitor.EjecutarProceso")
    public void ejecutarProceso(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.balanceador.monitor.Proceso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerProceso", targetNamespace = "http://monitor.balanceador.com/", className = "com.balanceador.monitor.ObtenerProceso")
    @ResponseWrapper(localName = "obtenerProcesoResponse", targetNamespace = "http://monitor.balanceador.com/", className = "com.balanceador.monitor.ObtenerProcesoResponse")
    public Proceso obtenerProceso(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "accept", targetNamespace = "http://monitor.balanceador.com/", className = "com.balanceador.monitor.Accept")
    @ResponseWrapper(localName = "acceptResponse", targetNamespace = "http://monitor.balanceador.com/", className = "com.balanceador.monitor.AcceptResponse")
    public void accept(
        @WebParam(name = "arg0", targetNamespace = "")
        CpuUsageSnapshot arg0);

}
